import std/unittest
import std/os
import std/strformat
import ../src/tinyusb

# Setup compiling of file "usb_descriptors.c" which contains descripors
# generated by TinyUSB's macros, used as a reference in following tests.
const
  TinyUsbPath {.strdefine.} = ""
  UsbDHeaderPath = TinyUsbPath / "src"
{.compile("usb_descriptors.c", fmt"-I{UsbDHeaderPath}").}


suite "Validate descriptors against TinyUSB macros":
  test "CDC inerface descriptor":
    let
      controlItf = 0.InterfaceNumber
      nimCdcDesc = initCompleteCdcSerialPortInterface(
        0.InterfaceNumber, 1, 8, 2, 512, 4.StringIndex
      )
      tusbCdcDesc {.importc: "desc_cdc_itf".}: array[sizeof(CompleteCdcSerialPortInterface), uint8]
    echo tusbCdcDesc[0]
