import std/unittest
import std/os
import std/strformat
import ../src/tinyusb

# Setup compiling of file "usb_descriptors.c" which contains descripors
# generated by TinyUSB's macros, used as a reference in following tests.
const
  TinyUsbPath {.strdefine.} = ""
  TinyUsbSrc = TinyUsbPath / "src"

{.passc: fmt"-I{TinyUsbSrc}".}
{.compile: "usb_descriptors.c".}

template toByteArray(sz: static[int], str: string): auto =
  var arr: array[sz, uint8]
  for (i, ch) in str.pairs:
    arr[i] = ch.uint8
  arr

suite "Validate descriptors against TinyUSB macros":

  test "CDC interface descriptor":
    const desclen = sizeof(CompleteCdcSerialPortInterface)
    let
      nimCdcDesc = initCompleteCdcSerialPortInterface(
        0.InterfaceNumber, 1, 8, 2, 64, 4.StringIndex
      )
      tusbCdcDesc {.importc: "desc_cdc_itf".}: array[desclen, uint8]

    let nimCdcDescArr = toByteArray(desclen, nimCdcDesc.serialize())

    check:
      nimCdcDesc.serialize.len == desclen
      tusbCdcDesc == nimCdcDescArr

  test "HID interface descriptor":
    const desclen = sizeof(CompleteHidInterfaceDescriptor)

    let
      tusbDesc {.importc: "desc_hid_itf".}: array[desclen, uint8]
      tusbReportDescLen {.importc: "desc_hid_report_size".}: uint16

    var nimDesc = initCompleteHidInterface(
      2.InterfaceNumber, tusbReportDescLen, 3, 16, 5, str=5.StringIndex
    )
    nimDesc.hid.hidVersion = initBcdVersion(1, 1, 1)

    let nimDescBytes = toByteArray(desclen, nimDesc.serialize)
    #echo "nim  ", nimDescBytes
    #echo "tusb ", tusbDesc
    check:
      nimDesc.serialize.len == desclen
      nimDescBytes == tusbDesc
