import std/unittest
import std/os
import std/strformat

# Setup compiling of file "usb_descriptors.c" which contains descripors
# generated by TinyUSB's macros, used as a reference in following tests.
const
  TinyUsbPath {.strdefine.} = ""
  UsbDHeaderPath = TinyUsbPath / "src"
{.compile("usb_descriptors.c", fmt"-I{UsbDHeaderPath}").}


suite "Validate descriptors against TinyUSB macros":
  setup:
    let
      tusbCdcDesc {.importc: "desc_cdc_itf", codegenDecl:"extern uint8_t $2[]".}: ptr UncheckedArray[uint8]
  test "CDC inerface descriptor":
    echo cast[int](tusbCdcDesc)
    echo isNil(tusbCdcDesc)
    echo tusbCdcDesc[0]
